/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NewtonCalc;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author sl3252
 */
public class Interface extends javax.swing.JFrame {
    
    private double initVel = 0;
    private double mass = 0;
    private double g = 0;
    private double radius = 0;
    private double massBase = 0;
    private int massPow = 0;
    private Planet planet;
    private Ball ball;
    private Persistor persistor;
    
    

    /**
     * Creates new form Interface
     */
    public Interface() {
        
        initComponents();
        //clearImages();
        
        persistor = new Persistor();
        
        orbitVelField.setEditable(false);
        escVelField.setEditable(false);
        gForceField.setEditable(false);
        trajTypeField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        panel2 = new java.awt.Panel();
        jComboBox1 = new javax.swing.JComboBox();
        gLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        inputLabel = new javax.swing.JLabel();
        initVelLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        radiusLabel = new javax.swing.JLabel();
        radiusField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        inputSeparator = new javax.swing.JSeparator();
        MassPowField = new javax.swing.JTextField();
        gField = new javax.swing.JTextField();
        initVelField = new javax.swing.JTextField();
        outputLabel = new javax.swing.JLabel();
        outputSeparator = new javax.swing.JSeparator();
        orbitVelLabel = new javax.swing.JLabel();
        orbitVelField = new javax.swing.JTextField();
        escVelLabel = new javax.swing.JLabel();
        escVelField = new javax.swing.JTextField();
        gForceLabel = new javax.swing.JLabel();
        gForceField = new javax.swing.JTextField();
        trajTypeLabel = new javax.swing.JLabel();
        trajTypeField = new javax.swing.JTextField();
        calcButton = new javax.swing.JButton();
        pathTypeLabel = new javax.swing.JLabel();
        gUnitLabel = new javax.swing.JLabel();
        initVelUnitLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        radiusUnitLabel = new javax.swing.JLabel();
        orbitVelUnitLabel = new javax.swing.JLabel();
        escVelUnitLabel = new javax.swing.JLabel();
        gForceUnitLabel = new javax.swing.JLabel();
        viewPrevButton = new javax.swing.JButton();
        MassBaseField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        fallImage = new javax.swing.JLabel();
        orbitImage = new javax.swing.JLabel();
        escImage = new javax.swing.JLabel();

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        gLabel.setText("Univ. G Constant");
        getContentPane().add(gLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 272, -1, -1));

        inputLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        inputLabel.setText("Input");
        getContentPane().add(inputLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, 30));

        initVelLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        initVelLabel.setText("Initial Velocity");
        getContentPane().add(initVelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 215, -1, -1));

        radiusLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        radiusLabel.setText("Radius of Planet");
        getContentPane().add(radiusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        radiusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiusFieldActionPerformed(evt);
            }
        });
        getContentPane().add(radiusField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 83, 36));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("Mass of Planet");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 22)); // NOI18N
        titleLabel.setText("Newton's Cannonball Calculator");
        getContentPane().add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));
        getContentPane().add(inputSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 50, 530, -1));

        MassPowField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MassPowFieldActionPerformed(evt);
            }
        });
        getContentPane().add(MassPowField, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 80, 40, 36));

        gField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gFieldActionPerformed(evt);
            }
        });
        getContentPane().add(gField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 83, 36));

        initVelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initVelFieldActionPerformed(evt);
            }
        });
        getContentPane().add(initVelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 83, 36));

        outputLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        outputLabel.setText("Output");
        getContentPane().add(outputLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 70, 30));
        getContentPane().add(outputSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 230, 520, -1));

        orbitVelLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        orbitVelLabel.setText("Orbital Velocity");
        getContentPane().add(orbitVelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 274, -1, -1));

        orbitVelField.setBackground(new java.awt.Color(204, 204, 204));
        orbitVelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orbitVelFieldActionPerformed(evt);
            }
        });
        getContentPane().add(orbitVelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 264, 83, 36));

        escVelLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        escVelLabel.setText("Escape Velocity");
        getContentPane().add(escVelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 314, -1, -1));

        escVelField.setBackground(new java.awt.Color(204, 204, 204));
        escVelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escVelFieldActionPerformed(evt);
            }
        });
        getContentPane().add(escVelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 304, 83, 36));

        gForceLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        gForceLabel.setText("Gravitational Force");
        getContentPane().add(gForceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 354, -1, -1));

        gForceField.setBackground(new java.awt.Color(204, 204, 204));
        gForceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gForceFieldActionPerformed(evt);
            }
        });
        getContentPane().add(gForceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 344, 83, 36));

        trajTypeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        trajTypeLabel.setText("Trajectory Type");
        getContentPane().add(trajTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 394, -1, -1));

        trajTypeField.setBackground(new java.awt.Color(204, 204, 204));
        trajTypeField.setToolTipText("skdljflkdsjflksdj");
        trajTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trajTypeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(trajTypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 384, 130, 36));

        calcButton.setText("Calculate");
        calcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonActionPerformed(evt);
            }
        });
        getContentPane().add(calcButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 40));

        pathTypeLabel.setText("Path Type");
        getContentPane().add(pathTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        gUnitLabel.setText("N⋅m2/kg2");
        getContentPane().add(gUnitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        initVelUnitLabel.setText("m/s");
        getContentPane().add(initVelUnitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel19.setText("x 10^");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 88, -1, 20));

        radiusUnitLabel.setText("km");
        getContentPane().add(radiusUnitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        orbitVelUnitLabel.setText("m/s");
        getContentPane().add(orbitVelUnitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 274, -1, -1));

        escVelUnitLabel.setText("m/s");
        getContentPane().add(escVelUnitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 314, -1, -1));

        gForceUnitLabel.setText("N");
        getContentPane().add(gForceUnitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 354, -1, -1));

        viewPrevButton.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        viewPrevButton.setText("View Previous Entries");
        viewPrevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPrevButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewPrevButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 458, 152, 40));

        MassBaseField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MassBaseFieldActionPerformed(evt);
            }
        });
        getContentPane().add(MassBaseField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 40, 36));

        jLabel24.setText("kg");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 88, -1, 20));

        fallImage.setIcon(new javax.swing.ImageIcon("/Users/sl3252/Dropbox/shana-li-y12/shana-li-repo/IA-shana-newton-calculator/fallback.png")); // NOI18N
        fallImage.setText("jLabel17");
        getContentPane().add(fallImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 170, -1));
        fallImage.getAccessibleContext().setAccessibleName("fallImage");

        orbitImage.setIcon(new javax.swing.ImageIcon("/Users/sl3252/Desktop/3jCw9AA - Imgur.gif")); // NOI18N
        orbitImage.setText("jLabel17");
        getContentPane().add(orbitImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 170, -1));
        orbitImage.getAccessibleContext().setAccessibleName("orbitImage");
        orbitImage.getAccessibleContext().setAccessibleDescription("");

        escImage.setIcon(new javax.swing.ImageIcon("/Users/sl3252/Dropbox/shana-li-y12/shana-li-repo/IA-shana-newton-calculator/exorbit.png")); // NOI18N
        escImage.setText("jLabel17");
        getContentPane().add(escImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 270, 170, -1));
        escImage.getAccessibleContext().setAccessibleName("escImage");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean isNumeric(String input){
        try {
            Double.parseDouble(input);
            return true;
        } catch (NumberFormatException err) {
            return false;
        }
    }
    
    private boolean isInt(String input){
        try{
            Integer.parseInt(input);
            return true;
        } catch (NumberFormatException err) {
            return false;
        }
    }
    
    private void clearImages() {
        orbitImage.setVisible(false);
        fallImage.setVisible(false);
        escImage.setVisible(false);
    }
    
    private void checkValues() throws Exception {
        
        if ("".equals(initVelField.getText()) || "".equals(MassBaseField.getText()) 
        || "".equals(MassPowField.getText()) || "".equals(gField.getText()) 
        || "".equals(radiusField.getText())){
            throw new Exception();
        }
                
        if (isNumeric(initVelField.getText()) && isNumeric(MassBaseField.getText()) 
        && isInt(MassPowField.getText()) && isNumeric(gField.getText()) 
        && isNumeric(radiusField.getText())) {
            initVel = Math.round(Double.parseDouble(initVelField.getText())*100.0)/100.0;
            massBase = Double.parseDouble(MassBaseField.getText());
            massPow = Integer.parseInt(MassPowField.getText());
            mass = Math.round(Math.pow(massBase, massPow)*100.0)/100.0;
            g = Math.round(Double.parseDouble(gField.getText())*100.0)/100.0;
            radius = Math.round(Double.parseDouble(radiusField.getText())*100.0)/100.0;
        } else {
            throw new Exception();
        }

        if (initVel <= 100000 && mass <= Math.pow(10, 30) && g <= 50 && radius <= 500000){
            initVelField.setText(String.valueOf(initVel));
            gField.setText(String.valueOf(g));
            radiusField.setText(String.valueOf(radius));
        } else {      
            throw new Exception();
        }
    }
    
    private void displayValues() {
       orbitVelField.setText(Double.toString(planet.getOrbitVel()));
       escVelField.setText(Double.toString(planet.getEscVel()));
       gForceField.setText(Double.toString(planet.getGForce()));
       trajTypeField.setText(ball.getPathType());

        switch (ball.getPathType()) {
            case "Fall Back":
                fallImage.setVisible(true);
                break;
            case "Orbit":
                orbitImage.setVisible(true);
                break;
            case "Escape":
                escImage.setVisible(true);
                break;
        }
    }
    
    private void radiusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiusFieldActionPerformed

    private void MassPowFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MassPowFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MassPowFieldActionPerformed

    private void gFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gFieldActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void initVelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initVelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initVelFieldActionPerformed
   
    private void orbitVelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orbitVelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orbitVelFieldActionPerformed

    private void escVelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escVelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escVelFieldActionPerformed

    private void gForceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gForceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gForceFieldActionPerformed

    private void trajTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trajTypeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trajTypeFieldActionPerformed

    private void calcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonActionPerformed
        
        try {
            checkValues();
        } 
        catch (Exception ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (planet == null) {
            planet = new Planet(g, mass, radius);
        }
        
        if (ball == null) {
            ball = new Ball(initVel);
        }
        
        if (persistor == null) {
            persistor = new Persistor();
        }
        
        clearImages();
        displayValues();
            
    }//GEN-LAST:event_calcButtonActionPerformed

    private void viewPrevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPrevButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewPrevButtonActionPerformed

    private void MassBaseFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MassBaseFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MassBaseFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MassBaseField;
    private javax.swing.JTextField MassPowField;
    private javax.swing.JButton calcButton;
    private javax.swing.JLabel escImage;
    private javax.swing.JTextField escVelField;
    private javax.swing.JLabel escVelLabel;
    private javax.swing.JLabel escVelUnitLabel;
    private javax.swing.JLabel fallImage;
    private javax.swing.JTextField gField;
    private javax.swing.JTextField gForceField;
    private javax.swing.JLabel gForceLabel;
    private javax.swing.JLabel gForceUnitLabel;
    private javax.swing.JLabel gLabel;
    private javax.swing.JLabel gUnitLabel;
    private javax.swing.JTextField initVelField;
    private javax.swing.JLabel initVelLabel;
    private javax.swing.JLabel initVelUnitLabel;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JSeparator inputSeparator;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel orbitImage;
    private javax.swing.JTextField orbitVelField;
    private javax.swing.JLabel orbitVelLabel;
    private javax.swing.JLabel orbitVelUnitLabel;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JSeparator outputSeparator;
    private java.awt.Panel panel2;
    private javax.swing.JLabel pathTypeLabel;
    private javax.swing.JTextField radiusField;
    private javax.swing.JLabel radiusLabel;
    private javax.swing.JLabel radiusUnitLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField trajTypeField;
    private javax.swing.JLabel trajTypeLabel;
    private javax.swing.JButton viewPrevButton;
    // End of variables declaration//GEN-END:variables
}
