/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NewtonCalc;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author sl3252
 */
public class NewtonCalcUI extends javax.swing.JFrame {
    
    private double initVel = 0;
    private double mass = 0;
    private double massBase = 0;
    private int massPow = 0;
    private double g = 0;
    private double gBase = 0;
    private int gPow = 0;
    private double radius = 0;

    
    private final Persister persister;
    private final Queue queue;
    
    

    /**
     * Creates new form Interface
     * @throws java.lang.Exception
     */
    public NewtonCalcUI() throws Exception {
        
        initComponents();
        clearImages();
        
        persister = new Persister();
        queue = new Queue();
        
        loadData();
        
        orbitVelField.setEditable(false);
        escVelField.setEditable(false);
        gForceField.setEditable(false);
        trajTypeField.setEditable(false);
        
        massBaseField.setText("5.97");
        massPowField.setText("24");
        gBaseField.setText("6.67");
        gPowField.setText("-11");
        radiusField.setText("6371");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        gLabel = new javax.swing.JLabel();
        inputLabel = new javax.swing.JLabel();
        initVelLabel = new javax.swing.JLabel();
        radiusLabel = new javax.swing.JLabel();
        radiusField = new javax.swing.JTextField();
        massLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        inputSeparator = new javax.swing.JSeparator();
        massPowField = new javax.swing.JTextField();
        gBaseField = new javax.swing.JTextField();
        initVelField = new javax.swing.JTextField();
        outputLabel = new javax.swing.JLabel();
        outputSeparator = new javax.swing.JSeparator();
        orbitVelLabel = new javax.swing.JLabel();
        orbitVelField = new javax.swing.JTextField();
        escVelLabel = new javax.swing.JLabel();
        escVelField = new javax.swing.JTextField();
        gForceLabel = new javax.swing.JLabel();
        gForceField = new javax.swing.JTextField();
        trajTypeLabel = new javax.swing.JLabel();
        trajTypeField = new javax.swing.JTextField();
        calcButton = new javax.swing.JButton();
        pathTypeLabel = new javax.swing.JLabel();
        gUnitLabel = new javax.swing.JLabel();
        initVelUnitLabel = new javax.swing.JLabel();
        massPowLabel = new javax.swing.JLabel();
        radiusUnitLabel = new javax.swing.JLabel();
        orbitVelUnitLabel = new javax.swing.JLabel();
        escVelUnitLabel = new javax.swing.JLabel();
        gForceUnitLabel = new javax.swing.JLabel();
        viewPrevButton = new javax.swing.JButton();
        massBaseField = new javax.swing.JTextField();
        massUniteLabel = new javax.swing.JLabel();
        fallImage = new javax.swing.JLabel();
        orbitImage = new javax.swing.JLabel();
        escImage = new javax.swing.JLabel();
        gPowField = new javax.swing.JTextField();
        massPowLabel1 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        gLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        gLabel.setText("Univ. G Constant");

        inputLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        inputLabel.setText("Input");

        initVelLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        initVelLabel.setText("Initial Velocity");

        radiusLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        radiusLabel.setText("Radius of Planet");

        radiusField.setToolTipText("The radius of the planet (6371km for Earth).");

        massLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        massLabel.setText("Mass of Planet");

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 22)); // NOI18N
        titleLabel.setText("Newton's Cannonball Calculator");

        massPowField.setToolTipText("The mass of the planet from which the ball is fired, in scientific notation.");

        gBaseField.setToolTipText("The Universal Gravitational Constant of the planet. In our universe it is about 6.67 x 10^-11.");

        initVelField.setToolTipText("The initial firing velocity of the cannonball, horizontally to the Earth's surface.");

        outputLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        outputLabel.setText("Output");

        orbitVelLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        orbitVelLabel.setText("Orbital Velocity");

        orbitVelField.setBackground(new java.awt.Color(204, 204, 204));
        orbitVelField.setToolTipText("The minimum projectile speed (less than esc. v) for a steady orbit.");

        escVelLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        escVelLabel.setText("Escape Velocity");

        escVelField.setBackground(new java.awt.Color(204, 204, 204));
        escVelField.setToolTipText("The minimum projectile speed to escape the gravitational field.");

        gForceLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        gForceLabel.setText("Gravitational Force");

        gForceField.setBackground(new java.awt.Color(204, 204, 204));
        gForceField.setToolTipText("Gravitational force of the planet.");

        trajTypeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        trajTypeLabel.setText("Trajectory Type");

        trajTypeField.setBackground(new java.awt.Color(204, 204, 204));
        trajTypeField.setToolTipText("Whether the projectile falls back to the planet, orbits the planet, or escapes orbit.");

        calcButton.setText("Calculate");
        calcButton.setToolTipText("Calculate!!");
        calcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonActionPerformed(evt);
            }
        });

        pathTypeLabel.setText("Path Type");
        pathTypeLabel.setToolTipText("The path that the projectile takes.");

        gUnitLabel.setText("N⋅m2/kg2");

        initVelUnitLabel.setText("m/s");

        massPowLabel.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        massPowLabel.setText("x 10^");

        radiusUnitLabel.setText("km");

        orbitVelUnitLabel.setText("m/s");

        escVelUnitLabel.setText("m/s");

        gForceUnitLabel.setText("N");

        viewPrevButton.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        viewPrevButton.setText("View Previous Entries");
        viewPrevButton.setToolTipText("Veiw a list of your previous 10 entries.");
        viewPrevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPrevButtonActionPerformed(evt);
            }
        });

        massBaseField.setToolTipText("The mass of the planet from which the ball is fired, in scientific notation.");

        massUniteLabel.setText("kg");

        fallImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewtonCalc/fallback.png"))); // NOI18N
        fallImage.setText("jLabel17");
        fallImage.setToolTipText("The ball will fall back to the planet's surface.");

        orbitImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewtonCalc/orbit.png"))); // NOI18N
        orbitImage.setText("jLabel17");
        orbitImage.setToolTipText("The ball will orbit around the planet.");

        escImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewtonCalc/exorbit.png"))); // NOI18N
        escImage.setText("jLabel17");
        escImage.setToolTipText("The ball will escape orbit, never to be seen again.");

        gPowField.setToolTipText("The Universal Gravitational Constant of the planet. In our universe it is about 6.67 x 10^-11.");

        massPowLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        massPowLabel1.setText("x 10^");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(titleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(inputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(inputSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(initVelLabel)
                        .addGap(25, 25, 25)
                        .addComponent(initVelField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(initVelUnitLabel)
                        .addGap(108, 108, 108)
                        .addComponent(massLabel)
                        .addGap(18, 18, 18)
                        .addComponent(massBaseField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(massPowLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(massPowField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(massUniteLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(gLabel)
                        .addGap(6, 6, 6)
                        .addComponent(gBaseField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(massPowLabel)
                        .addGap(6, 6, 6)
                        .addComponent(gPowField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(gUnitLabel)
                        .addGap(12, 12, 12)
                        .addComponent(radiusLabel)
                        .addGap(6, 6, 6)
                        .addComponent(radiusField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(radiusUnitLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(calcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(outputSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orbitVelLabel)
                            .addComponent(escVelLabel)
                            .addComponent(gForceLabel)
                            .addComponent(trajTypeLabel))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orbitVelField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(escVelField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(gForceField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trajTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orbitVelUnitLabel)
                            .addComponent(escVelUnitLabel)
                            .addComponent(gForceUnitLabel))
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(escImage, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orbitImage, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(pathTypeLabel))
                            .addComponent(fallImage, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(viewPrevButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(titleLabel)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(inputSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(initVelLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(initVelField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(initVelUnitLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(massLabel))
                    .addComponent(massBaseField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(massPowLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(massPowField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(massUniteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(gLabel))
                    .addComponent(gBaseField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(massPowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(gPowField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(gUnitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(radiusLabel))
                    .addComponent(radiusField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(radiusUnitLabel)))
                .addGap(3, 3, 3)
                .addComponent(calcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(outputSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(orbitVelLabel)
                        .addGap(23, 23, 23)
                        .addComponent(escVelLabel)
                        .addGap(23, 23, 23)
                        .addComponent(gForceLabel)
                        .addGap(23, 23, 23)
                        .addComponent(trajTypeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(orbitVelField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(escVelField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(gForceField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(trajTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(orbitVelUnitLabel)
                        .addGap(24, 24, 24)
                        .addComponent(escVelUnitLabel)
                        .addGap(24, 24, 24)
                        .addComponent(gForceUnitLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(escImage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(orbitImage))
                    .addComponent(pathTypeLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(fallImage)))
                .addGap(10, 10, 10)
                .addComponent(viewPrevButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        fallImage.getAccessibleContext().setAccessibleName("fallImage");
        orbitImage.getAccessibleContext().setAccessibleName("orbitImage");
        orbitImage.getAccessibleContext().setAccessibleDescription("");
        escImage.getAccessibleContext().setAccessibleName("escImage");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean isNumeric(String input) {
        try {
            Double.parseDouble(input);
            return true;
        } 
        catch (NumberFormatException e) {
            return false;
        }
    }
    
    private boolean isInt(String input){
        try {
            Integer.parseInt(input);
            return true;
        } 
        catch (NumberFormatException e) {
            return false;
        }
    }
    
    private void clearImages() {
        orbitImage.setVisible(false);
        fallImage.setVisible(false);
        escImage.setVisible(false);
    }
    
    private void loadData() throws Exception {
        File f = new File("data_do_not_modify.txt");
        
        if (f.exists()) {
            queue.add(persister.read());
        }
    }
    
    private void checkValues() {        
        if ("".equals(initVelField.getText()) || "".equals(massBaseField.getText()) 
        || "".equals(massPowField.getText()) || "".equals(gBaseField.getText()) 
        || "".equals(gPowField.getText()) || "".equals(radiusField.getText())){
            JOptionPane.showMessageDialog(null,"Fields cannot remain blank. "
                    + "Please fill out all the information.","Invalid Data",
                    JOptionPane.WARNING_MESSAGE);
        }
                
        if (!isNumeric(initVelField.getText()) || !isNumeric(massBaseField.getText()) || 
                !isInt(massPowField.getText()) || !isNumeric(gBaseField.getText()) || 
                !isInt(gPowField.getText()) || !isNumeric(radiusField.getText())) {
            JOptionPane.showMessageDialog(null,"Fields must be numeric. \n"
                + "Power fields must contain integers.",
                "Invalid Data", JOptionPane.WARNING_MESSAGE);
        } 
        else {
            initVel = Math.round(Double.parseDouble(initVelField.getText()) * 100.0) / 100.0;
            massBase = Double.parseDouble(massBaseField.getText());
            massPow = Integer.parseInt(massPowField.getText());
            mass = (Math.round(massBase * 100.0) / 100.0) * Math.pow(10, massPow);
            gBase = Double.parseDouble(gBaseField.getText());
            gPow = Integer.parseInt(gPowField.getText());
            g = (Math.round(gBase * 100.0) / 100.0) * Math.pow(10, gPow);
            radius = Math.round(Double.parseDouble(radiusField.getText()) * 100.0) / 100.0;
        }

        if (initVel <= 0 || initVel > 1000000000 || mass < Math.pow(10, 5) || mass > Math.pow(10, 50) 
                || g < Math.pow(10, -20) || g > Math.pow(10, -5) || radius <= 0 || radius > 500000) {  
            
            JOptionPane.showMessageDialog(null,"Fields cannot be zero, too small, or too big. \n"
                    + "Values that are too small may lead to inaccurately rounded results. \n"
                    + "The range (inclusive) of calculable values are as follows: \n \n"
                    + "Initial Velocity: 1 - 1000000000 m/s \n"
                    + "Mass: 10^5 - 10^30 kg \n"
                    + "G: 10^-20 - 10^-5 N⋅m2/kg2 \n"
                    + "Radius: 1 - 500000 km"
                    ,"Invalid Data", JOptionPane.WARNING_MESSAGE);
        } 
        else {
            initVelField.setText(String.valueOf(initVel));
            radiusField.setText(String.valueOf(radius));
        }
    }
    
    private void displayValues(Universe universe) {       
       orbitVelField.setText(Double.toString(universe.getPlanet().getOrbitVel()));
       escVelField.setText(Double.toString(universe.getPlanet().getEscVel()));
       gForceField.setText(Double.toString(universe.getPlanet().getGForce()));
       trajTypeField.setText(universe.getBall().getPathType());

        switch (universe.getBall().getPathType()) {
            case "Fall Back":
                fallImage.setVisible(true);
                break;
            case "Orbit":
                orbitImage.setVisible(true);
                break;
            case "Escape":
                escImage.setVisible(true);
                break;
        }
    }
       
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int choice = JOptionPane.showConfirmDialog(this,
        "Are you sure you want to exit?", "Exit Application",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (choice == JOptionPane.OK_OPTION) {
            try {
                persister.clear();
            } 
            catch (IOException e) {
            }
            
            if(!queue.getEmptiness()) {
                for (int i = 0; i <= queue.getLength(); i++) {
                    try {
                        persister.write(queue.dq());
                    } 
                    catch (IOException e) {
                    }
                }
            }
            
            System.exit(0);
        }
        else {
        }
    }//GEN-LAST:event_formWindowClosing

    private void viewPrevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPrevButtonActionPerformed
        JOptionPane.showMessageDialog(null, queue.toString(), "Previous Entries",
            JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_viewPrevButtonActionPerformed

    private void calcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonActionPerformed
        try {
            checkValues();
            clearImages();
            Universe universe = new Universe(initVel, g, massBase, massPow, mass, radius);
            displayValues(universe);
            queue.add(universe);
        }
        catch (Exception e) {
        }
    }//GEN-LAST:event_calcButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | 
                IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewtonCalcUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new NewtonCalcUI().setVisible(true);
            } 
            catch (Exception ex) {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcButton;
    private javax.swing.JLabel escImage;
    private javax.swing.JTextField escVelField;
    private javax.swing.JLabel escVelLabel;
    private javax.swing.JLabel escVelUnitLabel;
    private javax.swing.JLabel fallImage;
    private javax.swing.JTextField gBaseField;
    private javax.swing.JTextField gForceField;
    private javax.swing.JLabel gForceLabel;
    private javax.swing.JLabel gForceUnitLabel;
    private javax.swing.JLabel gLabel;
    private javax.swing.JTextField gPowField;
    private javax.swing.JLabel gUnitLabel;
    private javax.swing.JTextField initVelField;
    private javax.swing.JLabel initVelLabel;
    private javax.swing.JLabel initVelUnitLabel;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JSeparator inputSeparator;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField massBaseField;
    private javax.swing.JLabel massLabel;
    private javax.swing.JTextField massPowField;
    private javax.swing.JLabel massPowLabel;
    private javax.swing.JLabel massPowLabel1;
    private javax.swing.JLabel massUniteLabel;
    private javax.swing.JLabel orbitImage;
    private javax.swing.JTextField orbitVelField;
    private javax.swing.JLabel orbitVelLabel;
    private javax.swing.JLabel orbitVelUnitLabel;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JSeparator outputSeparator;
    private javax.swing.JLabel pathTypeLabel;
    private javax.swing.JTextField radiusField;
    private javax.swing.JLabel radiusLabel;
    private javax.swing.JLabel radiusUnitLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField trajTypeField;
    private javax.swing.JLabel trajTypeLabel;
    private javax.swing.JButton viewPrevButton;
    // End of variables declaration//GEN-END:variables
}
